server:
    port: 8080
    servlet:
      session:
          timeout: 5m
spring:
    mvc:
        hidden-method:
            filter:
                enabled: true
    profiles:
        active: dev
        include: secret
    threads:
        virtual:
            enabled: true
    datasource:
        url: jdbc:h2:./db_dev;MODE=MYSQL
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default_batch_fetch_size: 100
                format_sql: true
                highlight_sql: true
                use_sql_comments: true
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        clientId: ON_SECRET
                        scope: profile_nickname
                        client-name: Kakao
                        authorization-grant-type: authorization_code
                        redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
                    google:
                        client-id: ON_SECRET
                        client-secret: ON_SECRET
                        scope:
                            - email
                            - profile
                    naver:
                        client-id: ON_SECRET
                        client-secret: ON_SECRET
                        redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
                        authorization-grant-type: authorization_code
                        scope: name, email, nickname
                        client-name: Naver
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization_uri: https://nid.naver.com/oauth2.0/authorize
                        token_uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user_name_attribute: response
logging:
    level:
        com.ll.mb: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE
        org.hibernate.orm.jdbc.extract: TRACE
        org.springframework.transaction.interceptor: TRACE
custom:
    site:
        name: NEED_TO_INPUT
        baseUrl: "http://localhost:${server.port}"